# Generated by Django 5.0.2 on 2025-10-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_api', '0003_alumnos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='clave_alumno',
            new_name='clave_alumno',
        ),
    ]
