# Generated by Django 5.0.2 on 2025-10-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_api', '0005_maestros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='materias_json',
            new_name='materias_json_json',
        ),
    ]
