# Generated by Django 5.0.2 on 2025-10-21 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_api', '0006_rename_materias_maestros_materias_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='materias_json_json',
            new_name='materias_json',
        ),
    ]
