# Generated by Django 5.0.2 on 2025-12-02 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_api', '0007_rename_materias_json_json_maestros_materias_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=20, unique=True)),
                ('nombre_materia', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=50)),
                ('dias', models.JSONField(blank=True, default=list)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('salon', models.CharField(max_length=100)),
                ('programa_educativo', models.CharField(max_length=255)),
                ('creditos', models.PositiveIntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('profesor_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_escolar_api.maestros')),
            ],
        ),
    ]
